import { Inter } from "next/font/google";
import "react-loading-skeleton/dist/skeleton.css";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ClientWrapper from "./components/client-wrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientWrapper>{children}</ClientWrapper>
				<Toaster />
			</body>
		</html>
	);
}
